# Set all the thingz here. Go nuts. Seriously. Just remember to restart your
# server process after changing anything in here as the file is not reloaded
# automatically.

### SEO settings
title       : yabo
description : "A super lame theme."
keywords    : "Jekyll, theme, portfolio, blog, web"


### Site settings (all the technical thingz)
# url         : http://wolfgangcstrack.github.io
# baseurl     : "/yabo"


### Site settings (colors, pretty thingz, etc.)
# NOTE: color settings have been moved to _sass/_colors.scss
# If you want to customize site colors, change the variables in that file.


### Author settings
author:
  name      : Wolfgang C. Strack
  title     : Shiba Inu Enthusiast
  bio       : "I suck."
  thumb     : /images/author.jpg
  email     : wolfgangcstrack@gmail.com
  url       : http://wolfgang.github.io/
  github    : https://github.com/wolfgangcstrack
  facebook  : https://www.facebook.com/wolfgangcstrack
  linkedin  : https://www.linkedin.com/in/wolfgangcstrack/


### Jekyll stuff
destination : _site
sass:
  sass_dir  : _sass
  style     : compressed
exclude     : ["Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "*.sublime-*"]
timezone    : America/Los_Angeles